//! Tokenized stocks (V1.10, docs/v1.10-tokenized-stocks.md): each issuer's
//! own product registry → one `tokenized_security` per product, its edge to
//! the share it is tied to, and its deployments.
//!
//! | Issuer | Registry | Product identity | Edge to the share |
//! | --- | --- | --- | --- |
//! | Backed Assets (JE) Limited (xStocks) | `backed-api` | its own ISIN | `TRACKS` (tracker certificates) |
//! | Backpack Securities | `backpack` | its Solana mint | `TOKENIZES` (claim on an SPV holding the share, redeemable 1:1) |
//! | Robinhood Assets (Jersey) Limited | `rhj-api` | its registry uid | `TRACKS` (tracker certificates, V1.6) |
//!
//! The share is found **by identifier only**: a US ISIN's NSIN is its CUSIP
//! (ISO 6166; the US numbering agency is CUSIP Global Services), so an
//! ISIN `US<CUSIP><check>` names the imported equity keyed by that CUSIP;
//! Backpack states the CUSIP itself. The registry's ticker must then agree
//! with the equity's listing symbol: a disagreement rejects the match (it is
//! a check, never a way to find one). A product whose share is not an
//! imported equity is excluded and reported.
//!
//! The same matches give imported equities their ISIN, as the issuers state
//! it (never constructed from a CUSIP).
//!
//! Deployments are written to their own file (`deployments.json`): chains are
//! ingested by `undrly-collect onchain` from the chains themselves, so
//! deployments are ingested there, after them. Solana deployments are priced
//! by Jupiter, keyed by mint; their bars come from their deepest
//! GeckoTerminal pool (§13), declared here as that DEX's market.

use serde::{Deserialize, Serialize};
use undrly_core::{AssetNamespace, Caip2, ChainAsset, Isin};
use undrly_provider::{backed, backpack, binance, binance_bstocks, geckoterminal, rhj};

use super::*;

/// CAIP-2 of Solana mainnet (docs/v1.5-solana.md).
pub const SOLANA: &str = "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp";
/// CAIP-2 of Robinhood Chain mainnet (docs/v1.6-robinhood-chain.md).
pub const ROBINHOOD_CHAIN: &str = "eip155:4663";
/// CAIP-2 of BNB Smart Chain mainnet (V1.10).
pub const BNB_CHAIN: &str = "eip155:56";
/// Robinhood Chain's EIP-155 chain id.
const ROBINHOOD_CHAIN_ID: u64 = 4663;

/// A product issuer, by LEI. Reviewed 2026-10-04: the legal name from the
/// issuer's own documentation, the LEI from GLEIF (api.gleif.org).
struct Issuer {
    name: &'static str,
    lei: &'static str,
}

/// assets.backed.fi: "Backed Assets (JE) Limited" issues xStocks,
/// "tokenized tracker certificates"; GLEIF: BACKED ASSETS (JE) LIMITED.
const BACKED: Issuer = Issuer {
    name: "Backed Assets (JE) Limited",
    lei: "984500001AB7C6C7F577",
};

/// docs.robinhood.com/rhj; the same LEI V1.6 reads from the Final Terms.
const RHJ: Issuer = Issuer {
    name: "Robinhood Assets (Jersey) Limited",
    lei: "984500ADFHQZ9D6B9A29",
};

/// Binance's bStocks announcement (prnewswire, 2026-06-11): "bStocks are
/// issued by BTech Holdings Limited", prospectuses approved by ADGM's FSRA;
/// GLEIF: BTECH HOLDINGS LTD, Abu Dhabi.
const BTECH: Issuer = Issuer {
    name: "BTech Holdings Limited",
    lei: "25490057XTWK16I5YJ22",
};

/// The deployments file: each deployment `REPRESENTS` a product, asserted by
/// the issuer registry record named here (stored raw by `seed`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Deployments {
    pub dataset: String,
    pub version: u32,
    pub description: String,
    pub deployments: Vec<DeploymentRecord>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DeploymentRecord {
    pub key: String,
    pub id: String,
    /// CAIP-2.
    pub chain: String,
    pub asset_namespace: String,
    pub asset_reference: String,
    /// The product's canonical id.
    pub represents: String,
    /// The registry record asserting it.
    pub source: String,
    pub record_key: String,
    pub sha256: String,
}

impl Deployments {
    pub fn new(mut deployments: Vec<DeploymentRecord>) -> Self {
        deployments.sort_by(|a, b| a.key.cmp(&b.key));
        Self {
            dataset: "undrly-universe-deployments".into(),
            version: 1,
            description: "Generated by `undrly-collect universe build` from issuer registries (docs/v1.10-tokenized-stocks.md); ingested by `undrly-collect onchain` after the chains. Local/private use only.".into(),
            deployments,
        }
    }
}

/// The CUSIP inside a valid US ISIN.
pub(crate) fn us_cusip(isin: &str) -> Option<&str> {
    Isin::parse(isin).ok()?;
    isin.strip_prefix("US").and_then(|rest| rest.get(..9))
}

/// Listing symbols compared with the one class-share rule (`BRK-B` = `BRK.B`).
fn same_symbol(a: &str, b: &str) -> bool {
    a.replace('-', ".")
        .eq_ignore_ascii_case(&b.replace('-', "."))
}

struct Run<'e> {
    equities: &'e Equities,
    deployments: Vec<DeploymentRecord>,
    /// Equity build key → ISIN stated by an issuer.
    isins: BTreeMap<String, String>,
    products: BTreeMap<&'static str, usize>,
}

impl Run<'_> {
    /// The equity a stated identifier names, checked against the stated
    /// ticker; `Err(reason)` otherwise.
    fn share(&self, cusip: Option<&str>, ticker: Option<&str>) -> Result<EquityRef, String> {
        let Some(cusip) = cusip else {
            return Err("no US ISIN or CUSIP for the share".into());
        };
        let Some(e) = self.equities.get(cusip) else {
            return Err("the share is not an imported equity (sp500, nasdaq100)".into());
        };
        match ticker {
            Some(t) if same_symbol(t, &e.symbol) => Ok(e.clone()),
            other => Err(format!(
                "identifier names {} but the registry's ticker is {other:?}: rejected",
                e.symbol
            )),
        }
    }
}

fn issuer(ctx: &mut Ctx<'_>, i: &Issuer) -> Result<String, BuildError> {
    let key = format!("lei:{}", i.lei);
    let id = ctx.id(&key, Category::Entity)?;
    if !ctx.out.entities.contains_key(&key) {
        ctx.out.entities.insert(
            key.clone(),
            EntityRecord {
                key: key.clone(),
                id,
                kind: "company".into(),
                name: i.name.into(),
                lei: Some(i.lei.into()),
                cik: None,
            },
        );
        ctx.alias(&key, i.name, "name");
    }
    Ok(key)
}

struct Product<'a> {
    key: String,
    name: &'a str,
    isin: Option<&'a str>,
    symbol: Option<&'a str>,
    /// The edge to the share (`TRACKS` or `TOKENIZES`), when identified.
    share: Option<(&'static str, &'a EquityRef)>,
    issuer: Option<&'static Issuer>,
}

fn product(ctx: &mut Ctx<'_>, p: &Product<'_>) -> Result<String, BuildError> {
    let id = ctx.id(&p.key, Category::Instrument)?;
    ctx.out.instruments.insert(
        p.key.clone(),
        InstrumentRecord {
            key: p.key.clone(),
            id: id.clone(),
            class: "tokenized_security".into(),
            name: p.name.trim().to_owned(),
            isin: p.isin.map(str::to_owned),
            figi: None,
            contract_multiplier: None,
            unit_of_measure: None,
            base: None,
            quote: None,
        },
    );
    if let Some(symbol) = p.symbol {
        ctx.alias(&p.key, symbol, "symbol");
    }
    ctx.alias(&p.key, p.name, "name");
    if let Some((edge, share)) = p.share {
        ctx.out
            .relationships
            .insert((p.key.clone(), edge.into(), share.node.clone()));
    }
    if let Some(i) = p.issuer {
        let entity = issuer(ctx, i)?;
        ctx.out
            .relationships
            .insert((p.key.clone(), "ISSUED_BY".into(), entity));
    }
    Ok(id)
}

/// A deployment of `product` (build key, canonical id) asserted by the
/// registry file at `path`; Solana deployments also get a Jupiter feed.
fn deployment(
    ctx: &mut Ctx<'_>,
    run: &mut Run<'_>,
    path: &str,
    (product_key, product_id): (&str, &str),
    chain: &str,
    namespace: AssetNamespace,
    reference: &str,
) -> Result<(), BuildError> {
    let caip2 = Caip2::parse(chain).map_err(|e| BuildError::Invalid(e.to_string()))?;
    let asset = match ChainAsset::new(caip2.namespace(), namespace, reference) {
        Ok(a) => a,
        Err(e) => {
            ctx.exclude("tokenized / deployments", product_key, e.to_string());
            return Ok(());
        }
    };
    let key = format!(
        "deployment:{}",
        asset
            .caip19(&caip2)
            .map_err(|e| BuildError::Invalid(e.to_string()))?
    );
    let id = ctx.id(&key, Category::Deployment)?;
    let (entry, _) = ctx.file(path)?;
    run.deployments.push(DeploymentRecord {
        key,
        id,
        chain: chain.to_owned(),
        asset_namespace: namespace.as_str().to_owned(),
        asset_reference: asset.reference().to_owned(),
        represents: product_id.to_owned(),
        source: entry.source.clone(),
        record_key: entry.record_key.clone(),
        sha256: entry.sha256.clone(),
    });
    if chain == SOLANA {
        let usd = usd(ctx)?;
        ctx.feed(QuoteFeedRecord {
            source: "jupiter".into(),
            symbol: asset.reference().to_owned(),
            subject: product_key.to_owned(),
            unit: usd,
            basis: "aggregated".into(),
            venue: None,
            price_type: "last".into(),
            stale_after_seconds: Some(MARKET_STALE_AFTER),
            freshness_clock: None,
            inverted: false,
        });
    }
    Ok(())
}

fn xstocks(ctx: &mut Ctx<'_>, run: &mut Run<'_>) -> Result<(), BuildError> {
    let path = paths::BACKED_TOKENS;
    let tokens = backed::decode_tokens(ctx.file(path)?.1)?;
    if tokens.page.has_next_page {
        return Err(BuildError::Invalid(
            "Backed registry: more than one page; fetch every page".into(),
        ));
    }
    let section = "tokenized / xStocks (Backed)";
    let mut rows: Vec<&backed::Token> = tokens.nodes.iter().collect();
    rows.sort_by(|a, b| a.symbol.cmp(&b.symbol));
    for t in rows {
        let Some(isin) = t.isin.as_deref().filter(|i| Isin::parse(i).is_ok()) else {
            ctx.exclude(section, &t.symbol, "no valid product ISIN");
            continue;
        };
        let cusip = t.underlying_isin.as_deref().and_then(us_cusip);
        let share = match run.share(cusip, t.underlying_symbol.as_deref()) {
            Ok(s) => s,
            Err(reason) => {
                ctx.exclude(
                    section,
                    format!("{} ({:?})", t.symbol, t.underlying_isin),
                    reason,
                );
                continue;
            }
        };
        let underlying = t.underlying_isin.clone().expect("matched by it");
        run.isins.insert(share.key.clone(), underlying);
        let key = format!("backed:{isin}");
        let id = product(
            ctx,
            &Product {
                key: key.clone(),
                name: &t.name,
                isin: Some(isin),
                symbol: Some(&t.symbol),
                share: Some(("TRACKS", &share)),
                issuer: Some(&BACKED),
            },
        )?;
        *run.products.entry("xStocks (Backed)").or_default() += 1;
        for d in &t.deployments {
            if let Some(mint) = backed::solana_mint(d) {
                deployment(
                    ctx,
                    run,
                    path,
                    (&key, &id),
                    SOLANA,
                    AssetNamespace::Token,
                    mint,
                )?;
            }
        }
    }
    Ok(())
}

fn backpack_tokens(ctx: &mut Ctx<'_>, run: &mut Run<'_>) -> Result<(), BuildError> {
    let securities = backpack::decode_securities(ctx.file(paths::BACKPACK_SECURITIES)?.1)?;
    let assets = backpack::decode_assets(ctx.file(paths::BACKPACK_ASSETS)?.1)?;
    let mints: HashMap<&str, Vec<&str>> = assets
        .iter()
        .map(|a| {
            (
                a.symbol.as_str(),
                a.tokens
                    .iter()
                    .filter(|t| t.blockchain == backpack::SOLANA_BLOCKCHAIN)
                    .filter_map(|t| t.contract_address.as_deref())
                    .collect(),
            )
        })
        .collect();
    let section = "tokenized / Backpack Securities";
    let mut rows: Vec<&backpack::Security> = securities.iter().collect();
    rows.sort_by(|a, b| a.asset.cmp(&b.asset));
    let mut no_cusip = 0;
    for s in rows {
        if s.cusip.is_none() {
            no_cusip += 1;
            continue;
        }
        let mint = match mints.get(s.asset.as_str()).map(Vec::as_slice) {
            Some([one]) => *one,
            other => {
                ctx.exclude(
                    section,
                    &s.asset,
                    format!(
                        "{} Solana tokens in /api/v1/assets; exactly one expected",
                        other.map_or(0, <[_]>::len)
                    ),
                );
                continue;
            }
        };
        let share = match run.share(
            s.cusip.as_deref().filter(|c| cusip::is_valid(c)),
            backpack::us_symbol(&s.asset),
        ) {
            Ok(x) => x,
            Err(reason) => {
                ctx.exclude(section, &s.asset, reason);
                continue;
            }
        };
        let key = format!("backpack:{SOLANA}/token:{mint}");
        let name = format!("{} - Backpack Sec.", s.name.trim());
        let id = product(
            ctx,
            &Product {
                key: key.clone(),
                name: &name,
                isin: None,
                symbol: Some(&s.asset),
                share: Some(("TOKENIZES", &share)),
                issuer: None,
            },
        )?;
        *run.products.entry("Backpack Securities").or_default() += 1;
        deployment(
            ctx,
            run,
            paths::BACKPACK_ASSETS,
            (&key, &id),
            SOLANA,
            AssetNamespace::Token,
            mint,
        )?;
    }
    if no_cusip > 0 {
        ctx.exclude(
            section,
            format!("{no_cusip} securities"),
            "Backpack states no CUSIP: the share cannot be identified",
        );
    }
    Ok(())
}

fn robinhood(
    ctx: &mut Ctx<'_>,
    run: &mut Run<'_>,
    bound: &BTreeSet<String>,
) -> Result<(), BuildError> {
    let path = paths::RHJ_ASSETS;
    let assets = rhj::RhjProvider::new().decode_assets(ctx.file(path)?.1)?;
    let section = "tokenized / Robinhood Stock Tokens (RHJ)";
    let mut rows: Vec<&rhj::Asset> = assets.assets.iter().collect();
    rows.sort_by(|a, b| a.id.cmp(&b.id));
    for a in rows {
        let label = format!("{} ({:?})", a.token_symbol, a.isin);
        if a.status != "ASSET_STATUS_ACTIVE" {
            ctx.exclude(section, label, format!("status {}", a.status));
            continue;
        }
        if a.isin.as_ref().is_some_and(|i| bound.contains(i)) {
            ctx.exclude(
                section,
                label,
                "ingested from its reviewed Final Terms (data/reference/tokenized-securities.json)",
            );
            continue;
        }
        let cusip = a.isin.as_deref().and_then(us_cusip);
        let share = match run.share(cusip, Some(&a.token_symbol)) {
            Ok(s) => s,
            Err(reason) => {
                ctx.exclude(section, label, reason);
                continue;
            }
        };
        run.isins
            .insert(share.key.clone(), a.isin.clone().expect("matched by it"));
        let key = format!("rhj:{}", a.id);
        let id = product(
            ctx,
            &Product {
                key: key.clone(),
                name: &a.token_name,
                isin: None,
                symbol: None,
                share: Some(("TRACKS", &share)),
                issuer: Some(&RHJ),
            },
        )?;
        *run.products
            .entry("Robinhood Stock Tokens (RHJ)")
            .or_default() += 1;
        for d in a
            .deployments
            .iter()
            .filter(|d| d.chain_id == ROBINHOOD_CHAIN_ID)
        {
            deployment(
                ctx,
                run,
                path,
                (&key, &id),
                ROBINHOOD_CHAIN,
                AssetNamespace::Erc20,
                &d.contract_address,
            )?;
        }
    }
    Ok(())
}

/// Binance bStocks: products of BTech Holdings with their BNB Chain
/// deployment and Binance spot book. Binance's list states only the share's
/// ticker, so no edge to the share is asserted (docs §5).
fn bstocks(ctx: &mut Ctx<'_>, run: &mut Run<'_>) -> Result<(), BuildError> {
    let list = binance_bstocks::decode_list(ctx.file(paths::BSTOCKS)?.1)?;
    let info = binance::decode_exchange_info(ctx.file(paths::BINANCE_EXCHANGE_INFO)?.1)?;
    let markets: HashMap<&str, &binance::Market> = info
        .symbols
        .iter()
        .map(|m| (m.symbol.as_str(), m))
        .collect();
    let usdt = ctx.v1.id("usdt")?;
    let venue = ctx.node_ref("venue:binance");
    if !ctx.is_v1(&venue) {
        return Err(BuildError::Invalid(
            "Binance venue is not declared (run `fx build` before `universe build`)".into(),
        ));
    }
    let section = "tokenized / bStocks (Binance)";
    let mut rows: Vec<&binance_bstocks::Token> = list.data.iter().collect();
    rows.sort_by(|a, b| a.symbol.cmp(&b.symbol));
    let mut priced = 0;
    for t in rows {
        if t.kind != binance_bstocks::BSTOCK_TYPE || t.chain_id != "56" {
            ctx.exclude(
                section,
                &t.symbol,
                format!(
                    "type {} on chain {}: not a BNB Chain bStock",
                    t.kind, t.chain_id
                ),
            );
            continue;
        }
        let address = match ChainAsset::new(
            undrly_core::ChainNamespace::Eip155,
            AssetNamespace::Erc20,
            &t.contract_address,
        ) {
            Ok(a) => a.reference().to_owned(),
            Err(e) => {
                ctx.exclude(section, &t.symbol, e.to_string());
                continue;
            }
        };
        let key = format!("bstocks:{BNB_CHAIN}/erc20:{address}");
        let name = format!("{} bStock", t.ticker.trim());
        let id = product(
            ctx,
            &Product {
                key: key.clone(),
                name: &name,
                isin: None,
                symbol: Some(&t.symbol),
                share: None,
                issuer: Some(&BTECH),
            },
        )?;
        *run.products.entry("bStocks (Binance)").or_default() += 1;
        deployment(
            ctx,
            run,
            paths::BSTOCKS,
            (&key, &id),
            BNB_CHAIN,
            AssetNamespace::Erc20,
            &address,
        )?;
        // Its spot book, confirmed in Binance's own market list.
        let market = t.cs.as_deref().and_then(|cs| markets.get(cs));
        match market {
            Some(m)
                if m.status == "TRADING"
                    && m.quote_asset == "USDT"
                    && Some(m.base_asset.as_str()) == t.asset.as_deref() =>
            {
                ctx.feed(QuoteFeedRecord {
                    source: binance::SOURCE_ID.into(),
                    symbol: m.symbol.clone(),
                    subject: key.clone(),
                    unit: usdt.clone(),
                    basis: "venue".into(),
                    venue: Some(venue.clone()),
                    price_type: "mid".into(),
                    stale_after_seconds: Some(MARKET_STALE_AFTER),
                    freshness_clock: None,
                    inverted: false,
                });
                ctx.out
                    .relationships
                    .insert((key.clone(), "TRADES_ON".into(), venue.clone()));
                ctx.convert_usdt_to_usd(&key)?;
                priced += 1;
            }
            _ => ctx.exclude(
                section,
                &t.symbol,
                format!(
                    "spot market {:?} not trading against USDT on Binance: no quote feed",
                    t.cs
                ),
            ),
        }
    }
    ctx.out.notes.push(format!(
        "bStocks: {priced} with a Binance USDT book; no edge to any share (Binance states a ticker only)"
    ));
    Ok(())
}

/// Every issuer registry present in the manifest (each is optional).
pub(crate) fn tokenized(
    ctx: &mut Ctx<'_>,
    equities: &Equities,
    bound: &BTreeSet<String>,
) -> Result<Deployments, BuildError> {
    let mut run = Run {
        equities,
        deployments: Vec::new(),
        isins: BTreeMap::new(),
        products: BTreeMap::new(),
    };
    if has_file(ctx, paths::BACKED_TOKENS) {
        xstocks(ctx, &mut run)?;
    }
    if has_file(ctx, paths::BACKPACK_SECURITIES) && has_file(ctx, paths::BACKPACK_ASSETS) {
        backpack_tokens(ctx, &mut run)?;
    }
    if has_file(ctx, paths::RHJ_ASSETS) {
        robinhood(ctx, &mut run, bound)?;
    }
    if has_file(ctx, paths::BSTOCKS) && has_file(ctx, paths::BINANCE_EXCHANGE_INFO) {
        bstocks(ctx, &mut run)?;
    }
    if has_file(ctx, paths::GECKOTERMINAL_DEXES) {
        pools(ctx)?;
    }
    // Issuer-stated ISINs for imported equities (V1 objects keep theirs).
    let mut enriched = 0;
    for (key, isin) in &run.isins {
        if let Some(i) = ctx.out.instruments.get_mut(key)
            && i.isin.is_none()
        {
            i.isin = Some(isin.clone());
            enriched += 1;
        }
    }
    ctx.out.notes.push(format!(
        "tokenized stocks: {} products ({}), {} deployments; {enriched} equities gained the ISIN their tokens' issuers state",
        run.products.values().sum::<usize>(),
        run.products
            .iter()
            .map(|(k, n)| format!("{k} {n}"))
            .collect::<Vec<_>>()
            .join(", "),
        run.deployments.len(),
    ));
    Ok(Deployments::new(run.deployments))
}

/// A pool shallower than this (USD reserve, as GeckoTerminal states it) does
/// not chart a token.
const MIN_POOL_RESERVE_USD: u64 = 1_000;

/// Each Jupiter-priced Solana token's deepest GeckoTerminal pool (by USD
/// reserve, among the pools GeckoTerminal lists for it) → a `geckoterminal` feed on that
/// pool's DEX, priced in USD for the token's side. It carries bars only
/// (`history bars`); the token's quote stays Jupiter's.
fn pools(ctx: &mut Ctx<'_>) -> Result<(), BuildError> {
    let section = "tokenized / GeckoTerminal pools";
    let dexes = geckoterminal::decode_dexes(ctx.file(paths::GECKOTERMINAL_DEXES)?.1)
        .map_err(BuildError::Invalid)?;
    let dex_names: BTreeMap<String, String> = dexes
        .data
        .into_iter()
        .map(|d| (d.id, d.attributes.name))
        .collect();
    let usd = usd(ctx)?;
    let tokens: Vec<(String, String)> = ctx
        .out
        .feeds
        .values()
        .filter(|f| f.source == "jupiter")
        .map(|f| (f.symbol.clone(), f.subject.clone()))
        .collect();
    let mut declared = 0;
    for (mint, subject) in tokens {
        let path = format!("{}{mint}.json", paths::GECKOTERMINAL_POOLS);
        if !has_file(ctx, &path) {
            // Not looked up: Jupiter had no price for it at fetch time.
            continue;
        }
        let pools = geckoterminal::decode_pools(ctx.file(&path)?.1).map_err(BuildError::Invalid)?;
        let token = format!("solana_{mint}");
        let reserve = |p: &geckoterminal::Pool| {
            p.attributes
                .reserve_in_usd
                .as_deref()
                .and_then(|r| undrly_core::decimal::parse_canonical(r).ok())
        };
        let best = pools
            .data
            .iter()
            .filter(|p| p.kind == "pool")
            .filter(|p| {
                [&p.relationships.base_token, &p.relationships.quote_token]
                    .iter()
                    .any(|s| s.data.as_ref().is_some_and(|r| r.id == token))
            })
            .filter_map(|p| Some((reserve(p)?, p)))
            .max_by(|a, b| a.0.cmp(&b.0));
        let Some((depth, pool)) = best else {
            ctx.exclude(section, &mint, "no GeckoTerminal pool: no bars");
            continue;
        };
        if depth < undrly_core::Decimal::from(MIN_POOL_RESERVE_USD) {
            ctx.exclude(
                section,
                &mint,
                format!(
                    "deepest pool {} holds {depth} USD: no bars",
                    pool.attributes.address
                ),
            );
            continue;
        }
        let Some(dex) = pool.relationships.dex.data.as_ref().map(|d| d.id.clone()) else {
            ctx.exclude(section, &mint, "pool states no DEX: no bars");
            continue;
        };
        let venue_key = format!("venue:geckoterminal:solana:{dex}");
        let venue_id = ctx.id(&venue_key, Category::Venue)?;
        ctx.out
            .venues
            .entry(venue_key.clone())
            .or_insert_with(|| VenueRecord {
                key: venue_key.clone(),
                id: venue_id,
                name: format!(
                    "{} (Solana)",
                    dex_names.get(&dex).map_or(dex.as_str(), String::as_str)
                ),
                mic: None,
            });
        let is_base = pool
            .relationships
            .base_token
            .data
            .as_ref()
            .is_some_and(|r| r.id == token);
        ctx.feed(QuoteFeedRecord {
            source: geckoterminal::SOURCE_ID.into(),
            symbol: geckoterminal::feed_symbol(&pool.attributes.address, is_base),
            subject: subject.clone(),
            unit: usd.clone(),
            basis: "venue".into(),
            venue: Some(venue_key.clone()),
            price_type: "last".into(),
            stale_after_seconds: Some(MARKET_STALE_AFTER),
            freshness_clock: None,
            inverted: false,
        });
        ctx.out
            .relationships
            .insert((subject, "TRADES_ON".into(), venue_key));
        declared += 1;
    }
    ctx.out.notes.push(format!(
        "GeckoTerminal pools: {declared} Solana tokens charted from their deepest pool (bars only; quotes stay Jupiter's)"
    ));
    Ok(())
}
